### PR TITLE
Example

### PR DESCRIPTION
**Pull request by GrantBirki**
# Example

An example demonstrating branch deployments

### CODE REVIEW

**Comment by GrantBirki** [comment]
.deploy noop

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy main

**Comment by thinh2010** [comment]
.deploy

**Review by Brandylee24 — APPROVED** [review]

**Comment by arjun9** [comment]
.deploy

**Comment by dil-ntoth** [comment]
.lock

**Pull request closed without merging**
